# Generated by Django 3.1.7 on 2021-03-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=30)),
                ('Score', models.IntegerField(blank=True)),
                ('time_taken', models.TimeField(blank=True)),
            ],
        ),
    ]
