# Generated by Django 3.1.7 on 2021-03-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TakeQuiz', '0002_auto_20210314_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='quiz_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
