# Generated by Django 3.1.7 on 2021-03-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=32)),
                ('age', models.IntegerField(default=21)),
                ('phone', models.TextField(null=True)),
            ],
        ),
    ]
