# Generated by Django 3.1.7 on 2021-03-12 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_name', models.CharField(max_length=30)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateQuiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('questions', models.CharField(max_length=100)),
                ('options_A', models.CharField(max_length=100)),
                ('options_B', models.CharField(max_length=100)),
                ('options_C', models.CharField(max_length=100)),
                ('options_D', models.CharField(max_length=100)),
                ('correct_option', models.CharField(max_length=100)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreateQuiz.quiz')),
            ],
        ),
    ]
