# Generated by Django 3.1.7 on 2021-03-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreateQuiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_creator',
            name='quiz_id',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='Quiz_creator',
        ),
    ]
