# Generated by Django 3.1.7 on 2021-03-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateQuiz', '0003_questions_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='Question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='correct_option',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_A',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_B',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_C',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option_D',
            field=models.TextField(),
        ),
    ]
