# Generated by Django 3.1.7 on 2021-03-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateQuiz', '0004_auto_20210313_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='Question_no',
            field=models.IntegerField(null=True),
        ),
    ]
